FROM maven:3.9.8-eclipse-temurin-21 AS builder
WORKDIR /build
COPY pom.xml ./
RUN mvn dependency:go-offline -B
COPY . .
RUN mvn package -DskipTests

FROM gcr.io/distroless/java21-debian12
COPY --from=builder /build/target/usuarios-0.0.1-SNAPSHOT.jar usuario-service.jar
ENTRYPOINT ["java", "-jar", "usuario-service.jar"]